vector_db:
  index_name: "trading-bot-agent"

retriever:
  top_k: 3
  score_threshold: 0.5

embedding_model:
  provider: "huggingface"
  model_name: "text-embedding-3-large"

llm:
  google:
    provider: "google"
    model_name: "gemini-1.5-pro"
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"

tools:
  tavily:
    max_results: 5
